<?php

namespace App\Filament\Resources\EffectResource\Pages;

use App\Filament\Resources\EffectResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Artisan;

class CreateEffect extends CreateRecord
{
    protected static string $resource = EffectResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $record = parent::handleRecordCreation($data); // TODO: Change the autogenerated stub

        Artisan::call('app:ges'); // update effects.css sheet

        return $record;
    }

    protected function getHeaderActions(): array
    {
        return [

        ];
    }
}
